url: "https://www.brightdesigns.band" # the base hostname & protocol for your site, e.g. https://example.com
baseurl: ""

# Site settings
title: Bright Designs 
email: FIRSTNAME LASTNAME [at] gmail [dot] com
description: "Marching band shows that will make your students shine!"


# Team names, titles and social links
people:
- name: Brighton Barrineau
  pic: 1
  position: Arranger and Designer
  social:
    - title:
      url: 
    - title:
      url: 
    - title:
      url: 

- name: Trevor Schachner
  pic: 2
  position: Arranger and Designer
  social:
    - title:
      url: 
    - title: 
      url: 
    - title: 
      url: 

- name: Ryan Wilhite
  pic: 3
  position: Program Coordinator and Designer
  social:
    - title: 
      url: 
    - title: 
      url: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
