-- SP3 Task 2: slug_redirects (old show slug -> show) and updated_at on
-- arrangements and tags, for optimistic concurrency in lib/actions.
-- Safe on existing rows: ADD COLUMN ... DEFAULT now() NOT NULL fills every
-- existing row with the migration time (now() is stable, so Postgres 11+
-- stores it as a fast default without rewriting the table). Generated by
-- drizzle-kit; the ENABLE ROW LEVEL SECURITY line is added by hand, as in
-- 0002. Policies: drizzle/migrations/2026-10-08_slug_redirects_rls.sql.
CREATE TABLE "slug_redirects" (
	"old_slug" text PRIMARY KEY NOT NULL,
	"show_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "slug_redirects" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "arrangements" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "slug_redirects" ADD CONSTRAINT "slug_redirects_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "slug_redirects_show_id_idx" ON "slug_redirects" USING btree ("show_id");