-- SP3 Task 4: pending_uploads, the server's record of a signed upload until
-- completeUpload (lib/actions/uploads.ts) verifies the object and writes the
-- `files` row. Server-only (DATABASE_URL, table owner): RLS is enabled with
-- no policies, so PostgREST exposes nothing. Generated by drizzle-kit; the
-- ENABLE ROW LEVEL SECURITY line is added by hand, as in 0002/0003. New
-- table only: no existing rows are touched. Rows older than expires_at are
-- removed (with their objects) by scripts/cleanup-pending-uploads.ts.
CREATE TABLE "pending_uploads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"bucket" text NOT NULL,
	"path" text NOT NULL,
	"expected_mime" text NOT NULL,
	"expected_size" bigint NOT NULL,
	"show_id" integer,
	"arrangement_id" integer,
	"kind" text NOT NULL,
	"is_public" boolean NOT NULL,
	"original_name" text NOT NULL,
	"description" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + interval '24 hours' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pending_uploads" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE INDEX "pending_uploads_expires_at_idx" ON "pending_uploads" USING btree ("expires_at");
